// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9YTqmJUOBAi79HIoJCIzMYY1-Pj5_Szk',
    appId: '1:598871302072:web:6c5a40565474a37c01f94d',
    messagingSenderId: '598871302072',
    projectId: 'moda-app-44a2d',
    authDomain: 'moda-app-44a2d.firebaseapp.com',
    storageBucket: 'moda-app-44a2d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKygPruJBI04I4mXrLgxNK5pMrOgWanZw',
    appId: '1:598871302072:android:4ddf15599c9c4f6f01f94d',
    messagingSenderId: '598871302072',
    projectId: 'moda-app-44a2d',
    storageBucket: 'moda-app-44a2d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw5PIxsN5Jh8q8B6Px5jCxhokSQny5emU',
    appId: '1:598871302072:ios:a66c7d5b4322413301f94d',
    messagingSenderId: '598871302072',
    projectId: 'moda-app-44a2d',
    storageBucket: 'moda-app-44a2d.appspot.com',
    iosClientId: '598871302072-cqffpvtatoge7p4vvm0jiu29s0unoaur.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
